### ISSUE TITLE
JACUZZI (ARM) failing to unenroll on v112

### ISSUE THREAD

**Issue by NotDarkn** [FWNavy/CryptoSmite#1]
## Built Using?
EndeavourOS with KDE Plasma 6.0.1

## Describe your Issue?
Upon following the instructions for CryptoSmite, it fails to boot into Verified Mode automatically after rebooting (requiring me to manually enable OS verification) then it fails to unenroll.

## Conclusion
Either CryptoSmite is broken or ARM is unsupported, however it's very much the latter from what I've been told for the past 2 months.

### Note
If you use the CryptoSmite (S) option in a SH1MMER Legacy shim, it actually works rather than building an actual CryptoSmite shim.

The decryption password is: `Info-58-immense!NickName_Arabia-710`

**Comment by MunyDev** [comment]
That is because the crossystem binary is broken and we aren't sure how to proceed from there without changing chroots. We are currently working on this issue.

**Comment by NotDarkn** [comment]
You may want to check out SH1MMER'S CryptoSmite option then since that worked with JACUZZI instead.

**Comment by MunyDev** [comment]
Ah ok i see

**Comment by NotDarkn** [comment]
fixed in recent commits
