### ISSUE TITLE
Sh1mmer Legacy is not working.

### ISSUE THREAD

**Issue by psannetwork** [FWNavy/CryptoSmite#13]
Legacy SH1mmer does not boot up. When inserting a USB during recovery, it blacks out and nothing happens. The board used is kukui. This issue occurs on ASUS Chromebook Detachable CZ1. I've tested it on three units, but encountered the same problem every time.　What should I do?

**Comment by NotDarkn** [comment]
KUKUI has known issues with booting into its RMA shim, unfortunately there is nothing we can do about it.

**Comment by NotDarkn** [comment]
@MunyDev Please close the issue, ty. This is something neither you or me can do something about.

**Comment by MunyDev** [comment]
We can't do much about this issue, if we find a potential solution we will reopen it and discuss.
