### ISSUE TITLE
Can’t Boot Into USB

### ISSUE THREAD

**Issue by reaper360vr006** [FWNavy/CryptoSmite#16]
The USB Won’t Work Even After Following The Google Slides. Not Sure What I’m Doing Wrong

**Comment by blankuserrr** [comment]
> The USB Won’t Work Even After Following The Google Slides. Not Sure What I’m Doing Wrong

what board are you?

**Comment by reaper360vr006** [comment]
Grunt

**Comment by orphanlol** [comment]
it could be
<ul style="list-style: none;">
<li>Skill issue</li>
<li>Brain issue</li>
<li>USB issue</li>
<li>Board issue</li>
<ul>

**Comment by VFXKLIPS** [comment]
DO i need a flash drive

**Comment by Yeetusmans2048** [comment]
Press **ctrl**+**D**, and then press enter. Then after that, press **esc**+**↻**+**⏻** again. Now you'll want to put the flash drive in. It should work now

**Comment by MunyDev** [comment]
This issue is not resolvable, and will require self diagnosis. Try different usbs.
