### ISSUE TITLE
Need help with downgrading.

### ISSUE THREAD

**Issue by RacoonIsBetter** [FWNavy/CryptoSmite#19]
My kenver number is 0 and my board is hatch. When I boot an old image it doesn't allow it but when I go into sh1mmer and click the unenroll option it accepts the recovery image but I can't actually go  into the old OS after it's done with recovery and when I turn OS verify back on it says OS missing or damaged.

**Comment by MunyDev** [comment]
It depends on what you are downgrading to. Versions 112 and above have the best experience. If you plan on downgrading to v63 or smth, we don't provide support for those versions. Those are around 6 years old.
