### ISSUE TITLE
Out Of Space

### ISSUE THREAD

**Issue by Wildtick** [FWNavy/CryptoSmite#2]
### Built Using?
Lubuntu 23.10

### Describe your Issue?
Every time I boot into Cryptosmite to run the command it gives me a out of space error and fails to unenroll

**Comment by MunyDev** [comment]
How did you build it? Is it prebuilt or you built it yourself?

**Comment by Wildtick** [comment]
built myself

**Comment by MunyDev** [comment]
was there any errors inside of the builder?

**Comment by Wildtick** [comment]
nope nothing unusual

**Comment by Wildtick** [comment]
![IMG_0576](https://github.com/FWSmasher/CryptoSmite/assets/110534522/58eead21-a2a0-4f96-ad75-2269160f8320)

**Comment by MunyDev** [comment]
yea it chose your drive to place the stateful in it

**Comment by Wildtick** [comment]
so it's not a bug?

**Comment by MunyDev** [comment]
i mean it is chromium source for choosing the hard drive so probably isn't a bug
