### ISSUE TITLE
No valid image detected

### ISSUE THREAD

**Issue by olavito** [FWNavy/CryptoSmite#3]
I downgraded from v122 to v118. Now I don't know if even after downgrading the patch is still there but just in case it isn't: What should I do?
I'm on a corsola board

**Comment by MunyDev** [comment]
Can you send me an image of this issue?

**Comment by NotDarkn** [comment]
CORSOLA seems to have issues with booting into their own RMA shims, I'm currently testing a substitute shim to solve this issue.

**Comment by NotDarkn** [comment]
> I downgraded from v122 to v118. Now I don't know if even after downgrading the patch is still there but just in case it isn't: What should I do? I'm on a corsola board

New CORSOLA RMA shims and prebuilts have been made and uploaded to dl.osu.bio, please try to boot into them. If they no longer give "No valid image detected" or "Invalid image" errors, please close the issue, thanks!

**Comment by zek-c** [comment]
corsola has never worked with anything, Ill try the new shim later but i have doubts. im on 114 LTS 15437.91.0 which is a new version released february this year, never been on any version above 117 so if it doesnt work its just a corsola problem (rusty lenovo 100e gen 4)

**Comment by NotDarkn** [comment]
> corsola has never worked with anything, Ill try the new shim later but i have doubts. im on 114 LTS 15437.91.0 which is a new version released february this year, never been on any version above 117 so if it doesnt work its just a corsola problem (rusty lenovo 100e gen 4)

i've had multiple people test the new CORSOLA RMA shim and it had worked for them, including for people that used to get "No valid image" when using the old one. for those that still got "no valid image" when using the new RMA shim, they had simply forgotten to turn on Developer Mode so it should work lol

**Comment by zek-c** [comment]
no i used dev mode. are they on the new ARM lenovo 100e gen 4?

**Comment by zek-c** [comment]
i'll try it in around 30 min

**Comment by NotDarkn** [comment]
> i'll try it in around 30 min

11 hours later

**Comment by zek-c** [comment]
> > i'll try it in around 30 min
> 
> 
> 
> 11 hours later

i forgot lol but im doing it like actually right now im in progress of writing it to usb

**Comment by zek-c** [comment]
"cryptosmite.sh: not found"

**Comment by zek-c** [comment]
i'm using legacy sh1mmer version now i'll update soon

**Comment by zek-c** [comment]
legacy sh1mmer worked ❤️ thx fs

**Comment by zek-c** [comment]
nvm it still enrolled 💀 downgrading rn i'm on a newer LTS of 114

**Comment by zek-c** [comment]
ok it actually worked when i downgraded to an OLDER 114

**Comment by NotDarkn** [comment]
> "cryptosmite.sh: not found"

CORSOLA has issues when using CryptoSmite shims, for some odd reason, that's an issue up to Writable to fix.

**Comment by NotDarkn** [comment]
> ok it actually worked when i downgraded to an OLDER 114

Glad to hear the new shim worked and that you managed to unenroll. Please close the issue, thank you!

**Comment by zek-c** [comment]
tell olavito to do that i ain't open it 😭 @olavito use legacy sh1m for corsola it works

**Comment by MunyDev** [comment]
I'm closing the issue, it seems like it has been resolved.
