### ISSUE TITLE
cryptosmite.sh missing unenroll.tar.xz

### ISSUE THREAD

**Issue by NotDarkn** [FWNavy/CryptoSmite#4]
## Built Using?
EndeavourOS with KDE Plasma 6.0.1

## Describe your Issue?
Upon re-cloning my CryptoSmite mirror and then testing out the latest commit for cryptosmite.sh, everytime I attempt to run the command when booted into the shim it states the error following error:
```
localhost / # cryptosmite.sh
unenroll.tar.xz not found!
```
## Conclusion
~~The latest commit to make cryptosmite.sh use the SH1MMER Legacy variant needs to change the file name of the stateful (or chroot) .tar.xz file to be `stateful.tar.xz` rather than `unenroll.tar.xz`.~~ Tested this, didn't work. Honestly I'm not entirely sure except that CryptoSmite should revert the commit or change something in the file detection.

**Comment by MunyDev** [comment]
We know about this issue and we are actively trying to solve it. unenroll.tar.xz is equal to stateful2.tar.xz

**Comment by NotDarkn** [comment]
at least temporary revert the commit so then people can build CryptoSmite again

**Comment by MunyDev** [comment]
issue fixed in latest commit

**Comment by NotDarkn** [comment]
latest hotfix did not work

**Comment by MunyDev** [comment]
ok now the issue is fixed, use the enrollment branch to build new cryptomsite images

**Comment by NotDarkn** [comment]
fixed
