### ISSUE TITLE
Linux (penguin) crashes when a cmd is run

### ISSUE THREAD

**Issue by SlideShowGames** [FWNavy/CryptoSmite#5]
Might just be my cb but just saying

**Comment by MunyDev** [comment]
Are you on devmode?

**Comment by Wildtick** [comment]
bro cod is NOT going to run

**Comment by SlideShowGames** [comment]
I meant cmd also I fixed it

**Comment by SlideShowGames** [comment]
> bro cod is NOT going to run

lol imagine I tried to run the new mw3 on it
